### ISSUE TITLE
Add the new Holostars channels

### ISSUE THREAD

**Issue by hervis73** [vtstats/web#791]
A new Holostars unit (Uproar!) has recently been [announced](https://prtimes.jp/main/html/rd/p/000000644.000030268.html). Is it possible to add the following channels in Holostats:

- Yatogami Fuma : https://www.youtube.com/channel/UCc88OV45ICgHbn3ZqLLb52w
- Hizaki Gamma : https://www.youtube.com/channel/UCkT1u65YS49ca_LsFwcTakw
- Minase Rio : https://www.youtube.com/channel/UCdfMHxjcCc2HSd9qFvfJgjg
- Utsugi Uyu : https://www.youtube.com/channel/UCgRqGV1gBf2Esxh0Tz1vxzw

Since you are at it, is it possible to add the [official Holostars channel](https://www.youtube.com/channel/UCWsfcksUUpoEvhia0_ut0bA) as well, since the other Hololive channels (Official, Indonesia, English) are already in the instance?

Thank you very much for all your hard work!

**Comment by PoiScript** [comment]
I added holostars uproar members in commit f454043efc561183eaedae510514cdb6c7f64580.

As for the holostars official channel, I will add it today or tomorrow.

**Comment by PoiScript** [comment]
done.
