### ISSUE TITLE
Anyway to search for streams with specific Title

### ISSUE THREAD

**Issue by shoaibshakeel381** [vtstats/web#816]
This will help in finding streams of related games, or karoake etc.

**Comment by PoiScript** [comment]
Yes, it's actually in my plan. Since postgresql (the underlying database) supports full text search out of the box, it should be pretty straightforward to implement. Just stay tuned for now.

**Comment by PoiScript** [comment]
this feature has been implemented in vtstats :), to give it a try, go to https://vt.poi.cat/stream/live and type something in the text field.

<img width="744" alt="image" src="https://github.com/vtstats/web/assets/17513314/5af74d07-a73c-4ae1-86b1-2b9f6822a15c">
