### ISSUE TITLE
Channel updates have stopped since 09/17 03:00 (GMT+08:00), 500 INTERNAL_SERVER_ERROR since 09/17 19:40 (GMT+08:00)

### ISSUE THREAD

**Issue by JC-Chung** [vtstats/web#817]
[YouTube Channel](https://holo.poi.cat/youtube-channel) Updated at 09/17 03:00 (GMT+08:00)
[Bilibili Channel](https://holo.poi.cat/bilibili-channel) Updated at 09/17 04:00 (GMT+08:00)
The update function of the other two subpages works normally

500 INTERNAL_SERVER_ERROR since 09/17 19:40 (GMT+08:00)

順便問一下，大概多久更新沒正常運作時要來回報

**Comment by PoiScript** [comment]
I'll be closing this GitHub issue as it's currently outdated. you can now report problem to me directly in discord server: https://discord.com/invite/m9NwUzKbkK
