### ISSUE TITLE
Several HOLOSTARS channels missing

### ISSUE THREAD

**Issue by shopistar** [vtstats/web#829]
The new HOLOSTARS EN channels are still missing. They should be along the same category as Holostars English -Tempus-

Gavis Bettel: https://www.youtube.com/channel/UCHP4f7G2dWD4qib7BMatGAw
Machina X Flayon: https://www.youtube.com/channel/UC060r4zABV18vcahAWR1n7w
Banzoin Hakka: https://www.youtube.com/channel/UC7gxU6NXjKF1LrgOddPzgTw
Josuiji Shinri: https://www.youtube.com/channel/UCMqGG8BRAiI1lJfKOpETM_w

Also official HOLOSTARS channels are missing from the Hololive Official category

HOLOSTARS JP: https://www.youtube.com/channel/UCWsfcksUUpoEvhia0_ut0bA
HOLOSTARS EN: https://www.youtube.com/channel/UCJxZpzx4wHzEYD-eCiZPikg

**Comment by PoiScript** [comment]
done. 
<img width="806" alt="image" src="https://github.com/vtstats/web/assets/17513314/12a49729-02ba-42d3-878e-26f53668f431">
