### ISSUE TITLE
Mori Calliope's stream times

### ISSUE THREAD

**Issue by satsuki-sama** [vtstats/web#833]
The stream times for Mori Calliope are bugged. From November 2022 to May 2023, the Day view says she streamed for over 24 hours each day, sometimes more than 48 hours each day.

**Comment by PoiScript** [comment]
thanks for reporting this. and i'll be closing this issue as it appears to be outdated now.

<img width="864" alt="image" src="https://github.com/vtstats/web/assets/17513314/3c2bb3f2-35f9-4f28-b0f6-1ef7885cdfae">
